server.port: 9001
spring:
 datasource:
   url: jdbc:mysql://localhost:3306/metricdb
   username: root
   password: nikhil98jaiswal@
   driver-class-name: com.mysql.jdbc.Driver
 jpa:
  hibernate.ddl-auto: update
  generate-ddl: true
  show-sql: true
  
db:
 url: http://localhost:9000/WA-DB/Books
partner:
 url: http://localhost:9002/WA-PARTNER

management.endpoints.web.exposure.include: "*"

window.size: 5000
initial.delay: 10000
threshold.percentage: 50

httpconnpool:
  maxTotal: 10000
  defaultMaxPerRoute: 10000
  maxPerRoutes:
    -
      scheme: http
      host: localhost
      port: 9002
      maxPerRoute: 10000