server.port: 9001

  
db:
 url: http://localhost:9000/WA-DB/Books
partner:
 url: http://localhost:9002/WA-PARTNER

management.endpoints.web.exposure.include: "*"

window.size: 60000
initial.delay: 64000
threshold.percentage: 50

httpconnpool:
  maxTotal: 20000
  defaultMaxPerRoute: 20000
  maxPerRoutes:
    -
      scheme: http
      host: localhost
      port: 9002
      maxPerRoute: 20000